version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

  messenger:
    build:
      context: .
      dockerfile: apps/messenger/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    depends_on:
      - database
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth
      - messenger

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
