services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: dev
    volumes:
      - ./apps/web:/social-net
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - my_networks

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth
      - web
    networks:
      - my_networks

  auth:
    extends:
      file: docker-compose.base.yml
      service: auth

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  sqlx_cli:
    extends:
      file: docker-compose.base.yml
      service: sqlx_cli

networks:
  my_networks:
    driver: bridge

volumes:
  postgres_data:
  auth_target:
  cargo_cache:
  sqlx_cli_target:
