services:
  auth_test:
    container_name: auth_test
    extends:
      file: docker-compose.base.yml
      service: auth_base
    build:
      target: test
    env_file:
      - .env
    depends_on:
      - postgres_test

  postgres_test:
    container_name: postgres_test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    extends:
      file: docker-compose.base.yml
      service: postgres_base
    ports:
      - "5434:5432"
    env_file:
      - .env

  sqlx_cli_test:
    container_name: sqlx_cli_test
    build:
      target: seed
      args:
        - TARGET=test
    extends:
      file: docker-compose.base.yml
      service: sqlx_cli
    env_file:
      - .env
    environment:
      - DATABASE_URL=${POSTGRES_TEST_DATABASE_URL}
    depends_on:
      postgres_test:
        condition: service_healthy

networks:
  my_networks:
    driver: bridge

volumes:
  auth_target:
  cargo_cache:
  sqlx_cli_target:
