services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    volumes:
      - ./:/social-net
      - cargo_cache:/usr/local/cargo/registry
      - auth_target:/social-net/target
    ports:
      - "8000:8000"
    depends_on:
      prisma_cli:
        condition: service_completed_successfully
    env_file:
      - .env

  messenger:
    container_name: messenger
    build:
      context: .
      dockerfile: apps/messenger/Dockerfile
    volumes:
      - ./:/social-net
      - cargo_cache:/usr/local/cargo/registry
      - messenger_target:/social-net/target
    ports:
      - "8001:8000"
    depends_on:
      prisma_cli:
        condition: service_completed_successfully
    env_file:
      - .env

  prisma_cli:
    container_name: prisma_cli
    build:
      context: .
      dockerfile: libs/prisma_cli/Dockerfile
    volumes:
      - ./:/social-net
      - cargo_cache:/usr/local/cargo/registry
      - prisma_target:/social-net/target
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth
      - messenger

  database:
    container_name: pg_database
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d
          ${POSTGRES_DB_NAME}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env

volumes:
  postgres_data:
  auth_target:
  messenger_target:
  prisma_target:
  cargo_cache:
