[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
common = { path = "../../libs/common" }
database = { path = "../../libs/database" }
tokio = { version = "1.43.0", features = ["full"] }
